### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/genomics-workshop#74]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

~- [ ] Example code chunks run as expected~
~- [ ] Challenges / exercises run as expected~
~- [ ] Challenge / exercise solutions are correct~
- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
~- [ ] A schedule appears on the lesson homepage (e.g. not “00:00”)~
~- [ ] Each episode includes learning objectives~
~- [ ] Each episode includes questions~
~- [ ] Each episode includes key points~
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Only a few of the lesson release checklist points are applicable to the lesson overview pages. I've crossed out items that don't apply.

**Comment by ErinBecker** [comment]
Remove unused image with https://github.com/datacarpentry/genomics-workshop/pull/84

**Comment by ErinBecker** [comment]
Fixed a broken link with https://github.com/datacarpentry/genomics-workshop/pull/85

**Comment by ErinBecker** [comment]
Complete!

**Comment by ErinBecker** [comment]
This is just a quick message confirming that this lesson will be included in the release that @fmichonneau and I are preparing this week. The release is scheduled to go through on the 18th and to be announced to the community on the 24th.

**Comment by fmichonneau** [comment]
Repository released! :tada: https://doi.org/10.5281/zenodo.3260309
